version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: finance_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  airflow:
    image: apache/airflow:2.8.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://your_db_user:your_db_password@postgres:5432/finance_warehouse
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
volumes:
  pgdata:
